# Generated by Django 5.1.1 on 2024-09-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_instructions_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='preparation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7),
        ),
    ]
